### ISSUE TITLE
Cannot Get Rasa Working

### ISSUE THREAD

**Issue by btotharye** [scalableminds/chatroom#16]
I tried following your instructions for the rasa channel but not sure how to actually get to the react chat UI.  I have the channel loaded and running in my bot but not sure where the actual chat UI is supposed to be available at.

Thanks

**Comment by hotzenklotz** [comment]
Just open your website / HTML file and insert the Javascript code that will embed the Chatroom:

```
    <script src="./dist/Chatroom.js"></script>
    <script type="text/javascript">
window.chatroom = new window.Chatroom({
  title: "Chat with a bot",
  container: document.querySelector(".chat-container"),
  welcomeMessage: "Hi, I am Mike. Nice to meet you.",
  host: "https://mike.bots.scm.io",
});
</script>
```

Note, the `host` attribute. Point to wherever your bot is running. Perhaps `localhost`?

**Comment by btotharye** [comment]
yea I tried that but just get a blank page with no errors or any console messages

**Comment by btotharye** [comment]
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
    <title>Rasa Chatbot</title>
  </head>
  <body>
    <div class="chat-container"></div>
      <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/>
    <script type="text/javascript">
window.chatroom = new window.Chatroom({
  host: "localhost",
  title: "Rasa Chatbot",
  container: document.querySelector(".chat-container"),
  welcomeMessage: "Hello, how can I help?"
});
</script>
  </body>
</html>
```

**Comment by btotharye** [comment]
I tried 0.0.0.0:5002 as well not sure why I never even see the chatbot UI though since its using your s3 hosted version of the js file

**Comment by btotharye** [comment]
I was able to get it working by modifying the demo.html and just building it with yarn and running it, very odd either way

![image](https://user-images.githubusercontent.com/1426587/42030018-71e059d2-7a9f-11e8-88be-051f3edfa639.png)

**Comment by hotzenklotz** [comment]
Great to see that you got it working. Do you have any suggestions that we should change to make the setup easier?

**Comment by btotharye** [comment]
I'll look it over and see if there are any improvements I can make, was planning on using this as a chat option for a chatbot I have instead of having to write my own react channel.

**Comment by hotzenklotz** [comment]
Nice! I am looking forward to your pull requests :-D

**Comment by btotharye** [comment]
seems like I"m also getting `Target container is not a DOM element.` so not sure if I"m doing something wrong below is the html:
```

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    var chatroom = window.Chatroom({
      host: "http://0.0.0.0:5002",
      title: "Mycroft Help",
      container: document.querySelector(".container"),
      welcomeMessage: "Hello, How may I help you?"
    });
  </script>
</body>
</html>
```

**Comment by hotzenklotz** [comment]
Your container class is called `chat-container`. However, you try to mount the chat into a DOM element `.container`: `document.querySelector(".container")` :-)

As far as I can tell the S3 scripts can be loaded without any problems. Perhaps a browser extension is blocking it? Can you open https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@0.6.8/dist/Chatroom.js ?

**Comment by btotharye** [comment]
well this came from your example so how should it look?

**Comment by normanrz** [comment]
Please try `document.querySelector(".chat-container")`. I updated the Readme.

**Comment by btotharye** [comment]
ok now the chatbot loads minus the pretty CSS which I guess is cause it cannot load the css due to the promise rejections I'm getting.  I'm guessing cause maybe this is running at localhost and the scripts are at a https address maybe?

Unhandled promise rejection 
TypeError: NetworkError when attempting to fetch resource.

**Comment by btotharye** [comment]
ok I figured it out, I had to use http://localhost:5002 for the host and now it works :)

**Comment by normanrz** [comment]
Cool 👍

**Comment by PravinrajV** [comment]
I have installed and followed the instructions.
I have 3 terminals running --> Yarn serve, actions, bot.
When I type in the chatroom, I see that in the Bot terminal, but i dont get any response displayed in the Chatroom.

Screenshots attached.
Please help.
![04_ui_capture](https://user-images.githubusercontent.com/31581909/45912588-d13cf080-bdf1-11e8-8972-a4502f1aba0c.PNG)
![03_bot_capture](https://user-images.githubusercontent.com/31581909/45912589-d13cf080-bdf1-11e8-90a6-4e1953198eba.PNG)
![02_actions_capture](https://user-images.githubusercontent.com/31581909/45912590-d13cf080-bdf1-11e8-98ac-da0134fe515a.PNG)
![01_yarn_capture](https://user-images.githubusercontent.com/31581909/45912591-d1d58700-bdf1-11e8-8afc-ba3ae93d320c.PNG)

This is my index file:
```

<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    var chatroom = window.Chatroom({
      host: "http://localhost:5002",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?"
    });
    chatroom.openChat();
  </script>
</body>

```

**Comment by asaiyed10** [comment]
^ i am having the same issue @ PravinrajV 
Were you able to resolve this?

**Comment by PravinrajV** [comment]
Yes. It is resolved. I don’t know how.

Deleted all and redeployed.

**Comment by hotzenklotz** [comment]
@asaiyed10 Make sure to use the chatroom with the correct version of Rasa Core. (> `v0.11.7`)

**Comment by Brijeshlakkad** [comment]
@PravinrajV i m having same problem. And yes, I deleted all model files and done all steps of chatroom, but it's still not working.

**Comment by navodjanitha** [comment]
File "C:\Users\3c TECH\AppData\Roaming\Python\Python36\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "C:\Users\3c TECH\AppData\Roaming\Python\Python36\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "C:\Users\3c TECH\AppData\Roaming\Python\Python36\site-packages\sanic\router.py", line 452, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method OPTIONS not allowed for URL /webhooks/rest/webhook

I got this error when try to send message from chatroom
